<?php
// Simple recap view — HTML and optional PDF (via Dompdf)
require 'db.php';

$uuid = $_GET['uuid'] ?? '';
 $asPdf = isset($_GET['pdf']) && ($_GET['pdf']=='1' || $_GET['pdf']=='true');
 $asDownload = isset($_GET['download']) && ($_GET['download']=='1' || $_GET['download']=='true');
if (!$uuid) { echo "Missing uuid"; exit; }

$off = $pdo->prepare("SELECT party, role, version, data, accepted_by, accepted_at
                      FROM offers WHERE thread_uuid=? ORDER BY version ASC");
$off->execute([$uuid]);
$offers = $off->fetchAll();
if (!$offers) { echo "No offers for this thread."; exit; }

$latest = json_decode(end($offers)['data'] ?: '{}', true);
$parties = [];
$roles   = [];
$accepted = false;
foreach ($offers as $o) {
  $p = $o['party'] ?: 'User';
  $r = $o['role']  ?: 'Unknown';
  $parties[$p] = true;
  if (!isset($roles[$r])) $roles[$r] = $p;
  if (!empty($o['accepted_at'])) $accepted = true;
}
$latestVer = (int)end($offers)['version'];

$html = '<!doctype html><html><head><meta charset="utf-8"><title>Fixture Recap — '.htmlspecialchars($uuid).'</title>';
$html .= '<style>
  @page { margin: 18mm; }
  body{font-family:Arial,Helvetica,sans-serif;margin:0;color:#0f172a;font-size:12px;line-height:1.5}
  .brandbar{border-bottom:3px solid #0b2440;padding-bottom:6px;margin-bottom:12px}
  .brandbar .bn{font-size:13px;font-weight:bold;color:#0b6fa4;letter-spacing:1px}
  .brandbar .bs{font-size:10px;color:#555}
  h1{margin:6px 0 4px;font-size:22px;color:#0b2440}
  h2{margin:18px 0 8px;font-size:13px;color:#0b2440;border-bottom:1px solid #e5e7eb;padding-bottom:3px}
  .muted{color:#6b7280;font-size:11px}
  .status{display:inline-block;font-size:11px;font-weight:bold;padding:4px 10px;border-radius:12px;margin:6px 0}
  .status.agreed{background:#dff5f2;color:#0ea5a3}
  .status.neg{background:#fdf0dd;color:#d97706}
  table{border-collapse:collapse;width:100%;font-size:11px;margin-top:6px}
  td,th{border:1px solid #e5e7eb;padding:7px 9px;text-align:left;vertical-align:top}
  thead th{background:#0b2440;color:#fff}
  tbody th{background:#f1f5f9;width:30%}
  .docfooter{margin-top:24px;border-top:1px solid #e5e7eb;padding-top:6px;color:#94a3b8;font-size:10px;text-align:center}
</style>';
$html .= '</head><body>';
$html .= '<div class="brandbar"><span class="bn">CHARTERDESK</span> &nbsp; <span class="bs">Maritime fixture negotiation</span></div>';
$html .= '<h1>Fixture Recap</h1>';
$html .= '<div class="muted">Thread: '.htmlspecialchars($uuid).' &nbsp;|&nbsp; Generated: '.date('Y-m-d H:i').' &nbsp;|&nbsp; Latest: v'.$latestVer.'</div>';
$html .= $accepted ? '<div class="status agreed">STATUS: AGREED</div>' : '<div class="status neg">STATUS: NEGOTIATING</div>';

$html .= '<h2>Parties</h2>';
$html .= '<p><b>All:</b> '.htmlspecialchars(implode(', ', array_keys($parties))).'</p>';
$html .= '<p><b>By Role:</b> ';
foreach($roles as $role=>$name){ $html .= htmlspecialchars("$role: $name ") . '&nbsp;&nbsp;'; }
$html .= '</p>';

$html .= '<h2>Agreed Terms (Latest)</h2>';
$html .= '<table><tbody>';
foreach ($latest as $k=>$v){
  $html .= '<tr><th>'.htmlspecialchars($k).'</th><td>'.nl2br(htmlspecialchars(is_scalar($v)? (string)$v : json_encode($v))).'</td></tr>';
}
$html .= '</tbody></table>';

$html .= '<h2>History</h2>';
$html .= '<table><thead><tr><th>Version</th><th>Party</th><th>Role</th><th>Accepted By</th><th>Accepted At</th></tr></thead><tbody>';
foreach ($offers as $o){
  $html .= '<tr><td>'.(int)$o['version'].'</td><td>'.htmlspecialchars($o['party']?:'User').'</td><td>'.htmlspecialchars($o['role']?:'Unknown').'</td><td>'.htmlspecialchars($o['accepted_by']?:'').'</td><td>'.htmlspecialchars($o['accepted_at']?:'').'</td></tr>';
}
$html .= '</tbody></table>';

$html .= '<div class="docfooter">Generated by CharterDesk &middot; Built during an internship at Integrated Maritime Exchange (IME).</div>';

$html .= '</body></html>';

if ($asPdf) {
    if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
        echo "Dompdf (vendor) not available. Run: composer require dompdf/dompdf";
        exit;
    }
    require_once __DIR__ . '/vendor/autoload.php';
    $dompdf = new \Dompdf\Dompdf();
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4','portrait');
    $dompdf->render();
    $pdf = $dompdf->output();
  header('Content-Type: application/pdf');
  if ($asDownload) {
    header('Content-Disposition: attachment; filename="fixture_recap_'.htmlspecialchars($uuid).'.pdf"');
  } else {
    header('Content-Disposition: inline; filename="fixture_recap_'.htmlspecialchars($uuid).'.pdf"');
  }
  echo $pdf; exit;
}

echo $html;

?>
